config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  
  root "home#index"

  resources :plants
  resources :carts, only: [:show]
  resources :cart_details

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user 
    has_many :cart_details
    has_many :plants, through: :cart_details
end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
    belongs_to :cart 
    belongs_to :plant
end

app/models/plant.rb
class Plant < ApplicationRecord
    has_many :cart_details
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_details_controller.rb
class CartDetailsController < ApplicationController

    before_action :authenticate_user! 

    def create 
        plant_to_add = Plant.find(params[:plant_id])

        @cart = Cart.find_by(user_id: current_user.id)

        @cart_detail = CartDetail.new
        @cart_detail.cart = @cart 
        @cart_detail.plant = plant_to_add

        if @cart_detail.save
            flash[:success] = "successfully added a plant to cart"
            redirect_to cart_path(@cart)
        else
            flash[:failure] = "something went wrong"
            render plants_path, status: :unprocessable_entity
        end
    end

    def destroy 
        @cart_detail = CartDetail.find(params[:id])
        if @cart_detail.delete 
            flash[:success] = "Successfully removed plant from cart."
            redirect_to cart_path(@cart_detail.cart)
        else
            flash.now[:failure] = "whoops that didn't work. plant not removed"
            render "carts#show", status: :unprocessable_entity
        end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    before_action :authenticate_user!, only: [:show]

    def show
        @cart = Cart.find(params[:id])
    end


    

    def self.total_cost(cart)
        sum = 0
        cart.plants.each do |p|
            sum += p.price
        end
        sum
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index

    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    def index
        @plants = Plant.all
        # render json: @plants
    end

    def show 
        @plant = Plant.find(params[:id])
    end

    def new 
        @plant = Plant.new
    end

    def edit 
        @plant = Plant.find(params[:id])
    end

    def create 
        @plant = Plant.new(plant_params)
        if @plant.save
            flash[:success] = "New plant added to inventory!"
            redirect_to plant_path(@plant) 
        else
            flash.now[:failure] = "Something went wrong."
            render :new, status: :unprocessable_entity
        end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # When a user is created - they should have a cart created in the carts table
  def create
    @user = User.new(sign_up_params)
    if @user.save
      cart = Cart.create(user_id: @user.id)
      flash[:success] = "Successfully registered."
      redirect_to new_user_session_path
    else
      flash.now[:failure] = "Something went wrong"
      render :new, status: :unprocessable_entity
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :first_name, :last_name, :password, :password_confirmation)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<div class="container mb-3">
    <h1><%= current_user.first_name %>'s cart</h1>

    <div class="list-group">
        <% @cart.plants.each do |plant| %>
            <a href="/plants/<%= plant.id %>" class="list-group-item">
                 <%= image_tag plant.image_url, size: "40x40" %>
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><%= plant.common_name %></h5>
                    <small><%= plant.price %></small>
                </div>
                <div class="d-flex w-100 justify-content-between">
                    <small class="mb-1"><%= plant.scientific_name %></small>
                    
                </div>                
            </a>
            <small><%= link_to "Remove", cart_detail_path, data: { turbo_method: :delete, confirm: "Are you sure you want to remove this item from your card?" } %></small>
        <% end %>
    </div>

<div class="container d-flex align-items-end">
      <div class="d-flex flex-row">
            <div class="col">
                <h1>Total:</h1>
            </div>
            <div class="col">
                <%= CartsController::total_cost(@cart) %>
            </div>
        </div>
</div>
</div>

app/views/home/index.html.erb
<div class="container">
    <h1>Home</h1>
    <h3>Welcome back, <%= current_user.first_name %></p>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap CDN for CSS Bundle -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>



  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-md bg-warning-subtle" >
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>">
          <%= image_tag "plant-logo", size: "30x24", alt: "logo", class: "d-inline-block align-text-top" %>
          PlantShop
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="toggle navbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav">
            <%= link_to "Home", root_path, class: "nav-link" %>
            <%= link_to "Shop Plants!", plants_path, class: "nav-link" %>
            
            <% if current_user %>
              <%= link_to "My Cart", cart_path(current_user.cart), class: "nav-link" %>
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link"%>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <% end %>
            
          </div>
        </div>
      </div>
    </nav>

    <!-- Render any flash messages -->
    <% flash.each do |name, msg| %>
      <div class="<%= name %>">
        <%= msg %>
      </div>
    <% end %>
  


    <%= yield %>

    <!-- Bootstrap CDN for JS Bundle so navbar toggles correctly -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_with model: plant do |form| %>

<div class="form-group">
    <%= form.label :common_name, class: "form-label" %>
    <%= form.text_field :common_name, class: "form-control" %>
</div>

<div class="form-group">
    <%= form.label :scientific_name, class: "form-label" %>
    <%= form.text_field :scientific_name, class: "form-control" %>
</div>

<div class="form-group">
    <%= form.label :image_url, class: "form-label" %>
    <%= form.url_field :image_url, class: "form-control" %>
</div>

<div class="form-group">
    <%= form.label :price, class: "form-label" %>
    <%= form.number_field :price, step: 0.01, class: "form-control" %>
</div>

<div class="form-group">
    <%= form.label :quantity, class: "form-label" %>
    <%= form.number_field :quantity, in: 1.0..100, step: 1, class: "form-control" %>
</div>

<% if request.fullpath.include? "new" %>
    <div class="form-group">
        <%= form.submit "Add to inventory", class: "btn btn-warning form-control" %>
    </div>
<% else %>
    <div class="form-group">
        <%= form.submit "Update inventory item", class: "btn btn-warning form-control" %>
    </div>

<% end %>


<% end %>

app/views/plants/edit.html.erb
<div class="container col-md-6 my-4 ">

<%= render 'form', plant: @plant %>

</div>

app/views/plants/index.html.erb
<div class="container">
    <h1>Plants!</h1>


    <div class="flex-container">
    <% @plants.each do |plant| %>

    <div class="card">
        <%= image_tag "plant-logo", alt: "plant-image", class: "card-img-top" %>
        <div class="card-body">
            <h4 class="card-title"><%= plant.common_name %></h4>
            <p class="card-text"><%= plant.scientific_name %></p>
            <p class="card-text"><%= plant.price %></p>
            <%= button_to "Add to cart", cart_details_path(:plant_id => plant.id), method: :post, class: "btn btn-warning" %>
        </div>
    </div>


    <% end %>
    </div>
</div>

app/views/plants/new.html.erb
<div class="container col-md-6 my-4 ">

<%= render 'form', plant: @plant %>

</div>

app/views/plants/show.html.erb
<div class="container">

<h1>plant details</h1>

<div class="card">
    <%= image_tag "plant-logo", alt: "plant image", class: "card-img-top" %>
    <div class="card-body">
        <h3 class="card-title"><%= @plant.common_name %></h3>
        <p class="card-text"><%= @plant.scientific_name %></p>
        <p class="card-text">Price: <%= @plant.price %></p>
    </div>
</div>

</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<div class="container" style="width:100%;">
  <%- if controller_name != 'sessions' %>

  <div class="m-3 mx-auto col-6 d-flex justify-content-center">
    <%= link_to "Back to log in", new_user_session_path, class: "btn btn-sm btn-warning" %><br />
  </div>
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class="m-3 d-flex justify-content-center">
    <%= link_to "Register", new_user_registration_path, class: "btn btn-sm btn-warning" %><br />
  <% end %>
  </div>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <div class="m-3 d-flex justify-content-center">
    <%= link_to "Forgot your password?", new_user_password_path, class: "btn btn-sm btn-danger" %><br />
  <% end %>
  </div>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path %><br />
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path%><br />
  <% end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
    <% end %>
  <% end %>
</div>